const axios = require('axios');

const GITHUB_API_BASE = 'https://api.github.com';
const token = process.env.GITHUB_TOKEN;

if (!token) {
  console.warn('Warning: GITHUB_TOKEN is not set. GitHub operations will fail without a token.');
}

const githubHeaders = {
  Authorization: `token ${token}`,
  Accept: 'application/vnd.github+json'
};

const getAuthenticatedUser = async () => {
  if (!token) {
    throw new Error('GITHUB_TOKEN is required for GitHub push.');
  }

  const response = await axios.get(`${GITHUB_API_BASE}/user`, {
    headers: githubHeaders
  });
  return response.data.login;
};

const ensureRepository = async (owner, repoName) => {
  try {
    await axios.get(`${GITHUB_API_BASE}/repos/${owner}/${repoName}`, {
      headers: githubHeaders
    });
  } catch (error) {
    if (error.response && error.response.status === 404) {
      await axios.post(
        `${GITHUB_API_BASE}/user/repos`,
        {
          name: repoName,
          description: 'Generated by Jarvis AI System',
          private: false
        },
        {
          headers: githubHeaders
        }
      );
    } else {
      throw error;
    }
  }
};

const getFileSha = async (owner, repoName, filePath) => {
  try {
    const response = await axios.get(
      `${GITHUB_API_BASE}/repos/${owner}/${repoName}/contents/${encodeURIComponent(filePath)}`,
      { headers: githubHeaders }
    );
    return response.data.sha;
  } catch (error) {
    if (error.response && error.response.status === 404) {
      return null;
    }
    throw error;
  }
};

const pushToGitHub = async (files, repoName, prompt) => {
  const owner = await getAuthenticatedUser();
  await ensureRepository(owner, repoName);

  const pushedFiles = [];

  for (const file of files) {
    const base64Content = Buffer.from(file.content, 'utf8').toString('base64');
    const sha = await getFileSha(owner, repoName, file.path);

    const payload = {
      message: prompt,
      content: base64Content
    };

    if (sha) {
      payload.sha = sha;
    }

    const response = await axios.put(
      `${GITHUB_API_BASE}/repos/${owner}/${repoName}/contents/${encodeURIComponent(file.path)}`,
      payload,
      {
        headers: githubHeaders
      }
    );

    pushedFiles.push({
      path: file.path,
      url: response.data.content.html_url
    });
  }

  return {
    owner,
    repository: repoName,
    pushedFiles
  };
};

module.exports = {
  pushToGitHub
};
